FROM arm64v8/ubuntu:20.04
LABEL maintainer="Xenon Lucifer Diablo <code@nmnx.org>"
LABEL source="https://github.com/diabloxenon/opencl"

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH\
    RUST_VERSION=1.51.0 \
    RUSTUP_VERSION=1.23.1

ADD ./helpers /tmp/helpers

RUN apt-get update && apt-get install -y tzdata &&\
    echo "Europe/Switzerland" > /etc/timezone    &&\
    dpkg-reconfigure -f noninteractive tzdata &&\
    apt-get install -y --no-install-recommends\
    apt-utils\
    curl\
    gnupg2\
    ca-certificates\
    gcc\
    libc6-dev\
    clinfo &&\
    sh /tmp/helpers/add_intel_ocl.sh &&\
    sh /tmp/helpers/add_rust_lang.sh &&\
    apt-get remove -y --auto-remove \
    apt-utils \
    curl \
    gnupg2 \
    ; \
    rm -rf /var/lib/apt/lists/*;

CMD ["clinfo"]